const actionTypes = {
  GET_INVITE_REQUESTED: 'GET_INVITE_REQUESTED',
  GET_INVITE_REJECTED: 'GET_INVITE_REJECTED',
  GET_INVITE_FULFILLED: 'GET_INVITE_FULFILLED',

  ADD_FACT_REQUESTED: 'ADD_TO_INVITE_REQUESTED',
  ADD_FACT_REJECTED: 'ADD_TO_INVITE_REJECTED',
  ADD_FACT_FULFILLED: 'ADD_TO_INVITE_FULFILLED',

  FACT_ADDED: 'GUEST_ADDED'
};

export default actionTypes;
